/* This SAS program was automatically generated by Stat/Transfer */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\pub\w4\w4_sf_sev_cp_v6.0.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\pub\w4\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = w4_sf_se ;

proc format library = library ;
   value W4TD01F
      1 = '特別好'  
      2 = '比較好'  
      3 = '差不多'  
      4 = '比較差'  
      5 = '特別差'  
      6 = '不清楚'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W4TD02F
      1 = '特別好'  
      2 = '比較好'  
      3 = '差不多'  
      4 = '比較差'  
      5 = '特別差'  
      6 = '不清楚'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W4TD03F
      1 = '特別好'  
      2 = '比較好'  
      3 = '差不多'  
      4 = '比較差'  
      5 = '特別差'  
      6 = '不清楚'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W4TD04F
      1 = '特別樂意'  
      2 = '比較樂意'  
      3 = '差不多'  
      4 = '比較不樂意'  
      5 = '特別不樂意'  
      6 = '不清楚'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W4TD05F
      1 = '特別強'  
      2 = '比較強'  
      3 = '差不多'  
      4 = '比較弱'  
      5 = '特別弱'  
      6 = '不清楚'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W4TD06F
      1 = '經常'  
      2 = '有時'  
      3 = '偶而'  
      4 = '從不'  
      5 = '不清楚'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W4TD07F
      1 = '會'  
      2 = '不會'  
      3 = '不清楚'  
      97 = '不合理值'  
      99 = '未填答' ;
   value W4TD08F
      1 = '相當清楚'  
      2 = '還算清楚'  
      3 = '不太清楚'  
      4 = '不清楚'  
      97 = '不合理值'  
      99 = '未填答' ;

DATA library.&dataset ;
INFILE datafile LRECL=15;
INPUT
   STUD_ID  1-5             W4TD01  6                W4TD02  7             
   W4TD03  8                W4TD04  9                W4TD05  10            
   W4TD06  11               W4TD07  12               W4TD08  13            
   W4SUMERR  14             W4SUMMIS  15           ;                       

LABEL
   STUD_ID = "學生代碼"
   W4TD01 = "w4：導師評量:合作能力"
   W4TD02 = "w4：導師評量:領導力"
   W4TD03 = "w4：導師評量:自律"
   W4TD04 = "w4：導師評量:樂於服務或助人"
   W4TD05 = "w4：導師評量:抗壓性"
   W4TD06 = "w4：導師評量:鬱卒/沮喪"
   W4TD07 = "w4：導師評量:困難無法解決/會說?"
   W4TD08 = "w4：導師評量:學生家裡情況?"
   W4SUMERR = "w4：不合理值總和"
   W4SUMMIS = "w4：未填答總和" ;

FORMAT
   W4TD01 W4TD01F.          W4TD02 W4TD02F.          W4TD03 W4TD03F.       
   W4TD04 W4TD04F.          W4TD05 W4TD05F.          W4TD06 W4TD06F.       
   W4TD07 W4TD07F.          W4TD08 W4TD08F.        ;
                     

LENGTH
   STUD_ID 4                W4TD01 3                 W4TD02 3              
   W4TD03 3                 W4TD04 3                 W4TD05 3              
   W4TD06 3                 W4TD07 3                 W4TD08 3              
   W4SUMERR 3               W4SUMMIS 3 ;

      

RUN ;
