/* This SAS program was automatically generated by Stat/Transfer */

/* The following line should contain the complete path and name of your raw data file */
FILENAME datafile 'c:\pub\w4\w4_sf_testing_v6.0.dat' ;

/* The following line should contain the directory in which you wish your SAS file to be stored */
libname library 'c:\pub\w4\' ;

/* The following line contains the name (without the extension) for your SAS dataset */
%LET dataset = w4_sf_te ;

proc format library = library ;
   value NEWSEX
      1 = 'male'  
      2 = 'female' ;
   value PROGRAM
      1 = '國中'  
      2 = '普通學程'  
      3 = '綜合學程'  
      4 = '高職'  
      5 = '五專' ;
   value CLSPGM
      1 = '國中'  
      21 = '普通學程自然組'  
      22 = '普通學程非自然組'  
      23 = '普通學程自然組與社會組混合'  
      24 = '不分組'  
      31 = '綜合學程學術導向'  
      32 = '綜合學程非學術導向'  
      41 = '工業類'  
      42 = '商業類'  
      43 = '海事水產類'  
      44 = '家事類'  
      45 = '農業類'  
      46 = '藝術類'  
      47 = '醫事護理類'  
      48 = '普通科'  
      51 = '理工'  
      52 = '文商'  
      53 = '醫' ;
   value URBAN3F
      1 = '鄉村'  
      2 = '城鎮'  
      3 = '都市' ;
   value PRIVATE
      0 = '公立'  
      1 = '私立' ;
   value ANS
      0 = '答錯'  
      1 = '答對'  
      9 = '遺漏值' ;

DATA library.&dataset ;
INFILE datafile LRECL=113;
INPUT
   STUD_ID $ 1-6            W4SCH_ID $ 7-10          W4CLS_ID $ 11-15      
   GENDER  16               W4PGRM  17               W4CLSPGM  18-19       
   W4URBAN3  20             W4PRIV  21               W4STWT1A  22-41       
   W4STWT1B  42-60          CF03  61                 CF06  62              
   CF09  63                 CF14  64                 CF17  65              
   CF20  66                 CF21  67                 CF26  68              
   CF28  69                 CF32  70                 CF37  71              
   CF39  72                 CF40  73                 CF41  74              
   CF45  75                 CF46  76                 CF47  77              
   CF48  78                 CF49  79                 CF50  80              
   CF51  81                 CF52  82                 CF53  83              
   CHIN15  84               CHIN19  85               CHIN20  86            
   CHIN22  87               CHIN23  88               CHIN27  89            
   ENGL17  90               ENGL18  91               ENGL19  92            
   ENGL20  93               ENGL21  94               ENGL22  95            
   ENGL23  96               MATH21  97               MATH22  98            
   MATH23  99               MATH24  100              MATH25  101           
   MATH27  102              MATH28  103              MATH36  104           
   MATH39  105              MATH41  106              MATH45  107           
   MATH50  108              MATH51  109              MATH53  110           
   MATH54  111              MATH55  112              MATH56  113           
 ;                       

LABEL
   STUD_ID = "學生代碼"
   W4SCH_ID = "w4:學校代碼"
   W4CLS_ID = "w4:班級代碼"
   GENDER = "學生性別"
   W4PGRM = "w4:學程類別"
   W4CLSPGM = "w4:課程類別"
   W4URBAN3 = "w4:城鄉地區分層別(三層)"
   W4PRIV = "w4:公私立別"
   W4STWT1A = "w4:學生樣本權數(標準化過後)"
   W4STWT1B = "w4:學生樣本權數(依有學校代碼的子樣本，標準化過後)"
   CF03 = "一般分析能力題目，w4題本上順序v107"
   CF06 = "一般分析能力、數學題目，w4題本上順序v132"
   CF09 = "一般分析能力題目，w4題本上順序v130"
   CF14 = "一般分析能力、數學題目，w4題本上順序v128"
   CF17 = "一般分析能力題目，w4題本上順序v127"
   CF20 = "一般分析能力題目，w4題本上順序v108"
   CF21 = "一般分析能力題目，w4題本上順序v109"
   CF26 = "一般分析能力題目，w4題本上順序v129"
   CF28 = "一般分析能力、數學題目，w4題本上順序v133"
   CF32 = "一般分析能力題目，w4題本上順序v110"
   CF37 = "一般分析能力題目，w4題本上順序v134"
   CF39 = "一般分析能力、數學題目，w4題本上順序v131"
   CF40 = "一般分析能力、數學題目，w4題本上順序v136"
   CF41 = "一般分析能力、數學題目，w4題本上順序v135"
   CF45 = "一般分析能力、數學題目，w4題本上順序v118"
   CF46 = "一般分析能力、數學題目，w4題本上順序v119"
   CF47 = "一般分析能力題目，w4題本上順序v121"
   CF48 = "一般分析能力題目，w4題本上順序v122"
   CF49 = "一般分析能力、數學題目，w4題本上順序v120"
   CF50 = "一般分析能力題目，w4題本上順序v123"
   CF51 = "一般分析能力、數學題目，w4題本上順序v124"
   CF52 = "一般分析能力、數學題目，w4題本上順序v125"
   CF53 = "一般分析能力、數學題目，w4題本上順序v126"
   CHIN15 = "中文題目，w4題本上順序v103"
   CHIN19 = "中文題目，w4題本上順序v102"
   CHIN20 = "中文題目，w4題本上順序v106"
   CHIN22 = "中文題目，w4題本上順序v105"
   CHIN23 = "中文題目，w4題本上順序v104"
   CHIN27 = "中文題目，w4題本上順序v101"
   ENGL17 = "英文題目，w4題本上順序v112"
   ENGL18 = "英文題目，w4題本上順序v113"
   ENGL19 = "英文題目，w4題本上順序v111"
   ENGL20 = "英文題目，w4題本上順序v116"
   ENGL21 = "英文題目，w4題本上順序v114"
   ENGL22 = "英文題目，w4題本上順序v115"
   ENGL23 = "英文題目，w4題本上順序v117"
   MATH21 = "數學題目，w4題本上順序v146"
   MATH22 = "數學題目，w4題本上順序v139"
   MATH23 = "數學題目，w4題本上順序v143"
   MATH24 = "數學題目，w4題本上順序v153"
   MATH25 = "數學題目，w4題本上順序v152"
   MATH27 = "數學題目，w4題本上順序v148"
   MATH28 = "數學題目，w4題本上順序v145"
   MATH36 = "數學題目，w4題本上順序v144"
   MATH39 = "數學題目，w4題本上順序v151"
   MATH41 = "數學題目，w4題本上順序v150"
   MATH45 = "數學題目，w4題本上順序v149"
   MATH50 = "數學題目，w4題本上順序v137"
   MATH51 = "數學題目，w4題本上順序v141"
   MATH53 = "數學題目，w4題本上順序v147"
   MATH54 = "數學題目，w4題本上順序v140"
   MATH55 = "數學題目，w4題本上順序v142"
   MATH56 = "數學題目，w4題本上順序v138" ;

FORMAT
   GENDER NEWSEX.           W4PGRM PROGRAM.          W4CLSPGM CLSPGM.      
   W4URBAN3 URBAN3F.        W4PRIV PRIVATE.          CF03 ANS.             
   CF06 ANS.                CF09 ANS.                CF14 ANS.             
   CF17 ANS.                CF20 ANS.                CF21 ANS.             
   CF26 ANS.                CF28 ANS.                CF32 ANS.             
   CF37 ANS.                CF39 ANS.                CF40 ANS.             
   CF41 ANS.                CF45 ANS.                CF46 ANS.             
   CF47 ANS.                CF48 ANS.                CF49 ANS.             
   CF50 ANS.                CF51 ANS.                CF52 ANS.             
   CF53 ANS.                CHIN15 ANS.              CHIN19 ANS.           
   CHIN20 ANS.              CHIN22 ANS.              CHIN23 ANS.           
   CHIN27 ANS.              ENGL17 ANS.              ENGL18 ANS.           
   ENGL19 ANS.              ENGL20 ANS.              ENGL21 ANS.           
   ENGL22 ANS.              ENGL23 ANS.              MATH21 ANS.           
   MATH22 ANS.              MATH23 ANS.              MATH24 ANS.           
   MATH25 ANS.              MATH27 ANS.              MATH28 ANS.           
   MATH36 ANS.              MATH39 ANS.              MATH41 ANS.           
   MATH45 ANS.              MATH50 ANS.              MATH51 ANS.           
   MATH53 ANS.              MATH54 ANS.              MATH55 ANS.           
   MATH56 ANS. ;
       

LENGTH
   GENDER 3                 W4PGRM 3                 W4CLSPGM 3            
   W4URBAN3 3               W4PRIV 3                 CF03 3                
   CF06 3                   CF09 3                   CF14 3                
   CF17 3                   CF20 3                   CF21 3                
   CF26 3                   CF28 3                   CF32 3                
   CF37 3                   CF39 3                   CF40 3                
   CF41 3                   CF45 3                   CF46 3                
   CF47 3                   CF48 3                   CF49 3                
   CF50 3                   CF51 3                   CF52 3                
   CF53 3                   CHIN15 3                 CHIN19 3              
   CHIN20 3                 CHIN22 3                 CHIN23 3              
   CHIN27 3                 ENGL17 3                 ENGL18 3              
   ENGL19 3                 ENGL20 3                 ENGL21 3              
   ENGL22 3                 ENGL23 3                 MATH21 3              
   MATH22 3                 MATH23 3                 MATH24 3              
   MATH25 3                 MATH27 3                 MATH28 3              
   MATH36 3                 MATH39 3                 MATH41 3              
   MATH45 3                 MATH50 3                 MATH51 3              
   MATH53 3                 MATH54 3                 MATH55 3              
   MATH56 3 ;

        

RUN ;
